### ISSUE TITLE
Q: transactions

### ISSUE THREAD

**Issue by ivanjaros** [cockroachdb/pebble#1020]
The direct crud methods create transactions internally on their own. So if I want to do more than one operation, does it make more sense to create transaction manually and use it to perform the tasks, so I would save some performance by avoiding the creation of the other transactions?

**Comment by petermattis** [comment]
By transactions do you mean batches? Batches are not transactions which is why they are not named as such. Batches provide atomicity and durability, but not isolation or consistency. Assuming you mean batches, yes it is more efficient to group a set of operations in a single batch rather than perform them individually.

**Comment by ivanjaros** [comment]
correct, batches. ok, thanks, i thought so too, just wasn't sure.
