### ISSUE TITLE
perf: getInternal constantly allocates with even small keys (16B < 40KB) as well as (*pebble.Iterator).SeekGE do

### ISSUE THREAD

**Issue by moredure** [cockroachdb/pebble#1077]
Is it possible to reuse this data structure?
```go
	var buf struct {
		dbi Iterator
		get getIter
	}
```

**Comment by moredure** [comment]
especially this block needs to be reused

```i.keyBuf = append(i.keyBuf[:0], key.UserKey...)```
because of each time new iterator allocated keyBuf not reused

**Comment by moredure** [comment]
I have Get heavy application based on pebble.DB

**Comment by moredure** [comment]
I guess newIterInternal should be used here to avoid allocations

**Comment by moredure** [comment]
Is it better to use iterator instead of Get?

**Comment by moredure** [comment]
When I replaced Get with NewIterator things get better, but prefixOrFullSeekKey allocates anyway is it possible to put this byte slice into iterAlloc as well?

**Comment by moredure** [comment]
github.com/cockroachdb/pebble.(*Iterator).SeekGE /go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20210302170351-6eee4f6b45b1/iterator.go:488

**Comment by petermattis** [comment]
> Is it better to use iterator instead of Get?

If you're only retrieving a single key, `Get` is better as it can stop walking down the LSM as soon as it finds the key, while an `Iterator` is forced to examine all of the levels. `Get` has not be as heavily optimized to reduce allocations as `Iterator` as we (CRDB) never use `Get`. Patches are welcome to use something akin to `iterAlloc` on the `Get` path. Also be aware of #197 which is possible to fix, but not something we're going to tackle soon.

> When I replaced Get with NewIterator things get better, but SeekGE allocates prefixOrFullSeekKey anyway, is it possible to put this byte slice into iterAlloc as well? 

@sumeerbhola This allocation in `Iterator.SeekGE` is relatively new. Seems possible to store a buf in `iterAlloc` in order to avoid it.

**Comment by moredure** [comment]
Thanks, I guess I'll try to provide two patches, one for get and one for this allocation in SeekGE soon.

I'll try to put buffer allocated in SeekGE to iterAlloca as some custom field so later it will be able to be reused.

**Comment by moredure** [comment]
https://github.com/cockroachdb/pebble/pull/1078

**Comment by moredure** [comment]
@sumeerbhola https://github.com/cockroachdb/pebble/pull/1082

**Comment by moredure** [comment]
And yes, Get better than Iter SeekGE, Iterator becomes slower when database grows.

**Comment by moredure** [comment]
Recreated pull request to fix getIter allocation https://github.com/cockroachdb/pebble/pull/1094

**Comment by moredure** [comment]
Solved!
