### ISSUE TITLE
benchmark zfs vs ext4

### ISSUE THREAD

**Issue by lunevalex** [cockroachdb/pebble#1136]
Now that customers are using ZFS in production we should benchmark throughput, file creation and deletion performance, sync performance, etc.

Historical context from @petermattis: we used to run the clearrange roachtest on ZFS. The performance was bad so we switched back to ext4. Simply enabling ZFS on storage roachtests might cause those tests to become flaky. Something to be prepared for.

**Comment by itsbilal** [comment]
As part of this issue, I imagine we'd want microbenchmarks that:

1) create a lot of files,
2) delete a lot of files with data in them (the writing of data being outside the timer), and
3) write to files then start timer, call Sync, stop timer.

If these are added behind the `pebble bench` command, it should be straightforward to run them on roachprod nodes, similar to how the `pebble/` roachtests work. There's already support in roachprod to specify the FS of volumes when creating clusters. 

Another helpful benchmark I can think of is crafting pebble Options that generates a lot of small SSTs, then running the existing ycsb-A benchmark with those options on different FSes manually. Only downside of an end-to-end workload like that is that deletion performance will get ignored, but at least file creation / sync performance will get tested.

**Comment by petermattis** [comment]
I'd be interested in the following:
* File creation performance when there are a large number of files in a directory (~100k). Is there any difference in performance for creating a file when a directory has a few files vs a large number of files? Creation would include creating the file and performing a sync on the parent directory.
* File deletion performance when there are a large number of files in a directory (~100k). We should benchmark deletion of individual files, as well as deletion of a large number of files as sometimes happens after a compaction.
* File deletion performance for a large file (128MB) vs a small file (2MB). I expect the performance to be similar, but worth verifying that expectation.

**Comment by jbowens** [comment]
While we're benchmarking, maybe it's also worth double-checking that `(pebble/vfs.FS).GetDiskUsage` (the `statfs` syscall) is constant-time on ZFS. @itsbilal checked [here](https://github.com/cockroachdb/pebble/pull/981#issuecomment-730085402). I'm not sure if he also tried with various disk usage and file counts?

**Comment by bananabrick** [comment]
I wrote down some results here: https://github.com/bananabrick/random/blob/master/results.md

LMK, if anyone wants to see some other benchmarks, or benchmarks following some different methodology.

**Comment by itsbilal** [comment]
Another part of this issue (that can also be filed as a separate issue) is turning on zfs for some roachtests. As deletes seem to be the operation with the biggest difference in performance between ext4 and zfs, occasionally running the `clearrange` roachtest on zfs for correctness reasons seems like a good idea. That roachtest could be modified to randomly use zfs on some iterations, just like how it randomly enables encryption-at-rest on some iterations right now.

Another good idea would be to run a variation of a write-heavy benchmark, eg. `ycsb/A`, regularly on zfs - anything write heavy will also generate more deletions, and it'll be interesting to see how it compares. Since the existing ycsb roachtest is a benchmark that shows up on the roachperf dashboard, it might be necessary to fork a separate `ycsb/A/zfs` roachtest that always runs on zfs, so as to not muddy up the existing ext4 performance metrics. Alternatively, one of the tpcc roachtests could be a good one to have a zfs variant of - as tpcc is also heavy and pretty balanced across reads/writes.

There might be some additional work involved in being able to easily change the fs for roachtests, such as moving some roachtests onto non-local-ssd machine types, as currently roachprod only lets you `reformat` if you have an EBS-backed machine. If there's a way to start up local-ssd nodes with ZFS from the start, that'd be preferable, but it'd involve more investigation.

**Comment by lunevalex** [comment]
issue for roachtest https://github.com/cockroachdb/cockroach/issues/65020

**Comment by bananabrick** [comment]
Closing this out, since I don't think there's any more work here.
