### ISSUE TITLE
db: concurrent manual compactions

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#1404]
In the context of CockroachDB, when excessive write load inverts an LSM, it's sometimes necessary to take a node offline and perform a manual compaction of a store. While we should focus most of our energy on preventing LSM inversions, a small amount of energy optimizing manual compactions might go a long way in reducing the pain of recovery.

A manual compaction only ever uses 1 of the concurrent compaction allotment. It runs 1 compaction of one level into the next, top-down. When we take a node offline and compact its store, there is no need to be considerate of user traffic. Running a single compaction one at a time doesn't make full use of available resources. We could perform multiple compactions from level _L_ to level _L_+1 in parallel, as long as the keyspaces of the two compactions are non-overlapping.

It might be a fun flex friday project to add an optional concurrency option to `(*DB).Compact` that allows the manual compaction to use compaction concurrency up to the minimum of the passed concurrency and the database's configured maximum concurrency.

**Comment by bananabrick** [comment]
@jbowens Are you already working on this?

**Comment by jbowens** [comment]
@bananabrick Naw, just wanted to document it

**Comment by sumeerbhola** [comment]
(To add to the list of benefits) Smaller compactions are easier to debug in terms of understanding throughput etc. We had a case where a single compaction (no idea about the levels involved) had been running for longer than 6 days (offline compaction of a CockroachDB node). Since it had not completed, there was no update to the MANIFEST during those 6 days. The only way to see if any progress was being made was to look at the pebble directory and see if new ssts were being written.
