### ISSUE TITLE
batch&wal: questions about the large batch

### ISSUE THREAD

**Issue by zhenyuxie** [cockroachdb/pebble#1464]
Hi, I read pebble's source code recently and there are some doubts  about the large batch as follows:
1. When a batch's memTableSize >= largeBatchThreshold, it is appended to mem.queue, but the current active mutable memtable will be forced to flush. So my question is why process the large batch separately and what's benefit of doing so?

2. In the function DB.commitWrite, I found the large batch will write wal before makeRoomForWrite. I tried to read comments to understand the purpose of this.  According to my understanding, just the batch is written to the current log rather than the newly generated log later,  but I still don't understand the benefits of doing this.

So, please help to answer the questions above, thanks.

**Comment by jbowens** [comment]
Hi @zhenyuxie,

1. There's some additional historical context in #12. In Pebble, a memtable's memory is allocated upfront in a fixed size arena. If a batch is larger than the memtable's size, it can't be written to the memtable. In order to still support arbitrarily-sized batches, Pebble avoids copying these large batches into memtable arenas altogether. The threshold for a 'large batch' is set to ½ the memtable size. I believe this is based on the observation that if a batch is small enough to fit in the memtable but large enough to mostly fill the memtable, it can avoid paying the cost of copying the batch into the memtable's memory when both the existing memtable's contents and the batch's contents will need to be flushed imminently.

2. Memtables and logs maintain a one-to-one relationship. If a memtable is flushed and the flush's sstables are linked into the LSM, the corresponding log file is simulatenously marked as obsolete so that it won't be replayed on Open. If the large batch was written to the _new_ log, Pebble would have already flushed the large batch to sstables but also have an active WAL containing the large batch's contents. If the process crashed and the database re-opened, Pebble would incorrectly re-apply the large batch's contents from the WAL effectively "double-writing" the large batch. This would violate invariants, and produce incorrect results for `MERGE` or `SINGLEDEL` keys.

**Comment by zhenyuxie** [comment]
Thanks @jbowens , I think I see what you mean. Looking forward to more communication with you, thinks again.

**Comment by petermattis** [comment]
See https://github.com/cockroachdb/pebble/blob/master/docs/rocksdb.md#large-batches for another description of the rationale behind Pebble's large batch handling. I'm going to close this issue out under the assumption that your questions have been adequately answered.
