### ISSUE TITLE
Arbitrary large uncommitted batches

### ISSUE THREAD

**Issue by asdine** [cockroachdb/pebble#1468]
https://github.com/cockroachdb/pebble/issues/12 adds support for arbitrary size write batches but it seems the hard limit is 4 GB. Is there a way to write even more (rollbackable) data without having to implement our own WAL?

**Comment by petermattis** [comment]
I'm not sure what you mean by "rollbackable" in this context. A batch commits atomically when it is written, but it is either committed or not-committed. There isn't really a rollback step here as there is in traditional transaction commit.

I can't recall all of the reasons behind the 4 GB limit. I think there may be some data structures that were inherited from RocksDB, perhaps in the batch representation. It is likely feasible to lift that limit, but a very large batch like that comes with two very significant overheads: the batch needs to be written to the WAL (and writing a 4+ GB batch will be slow), and the batch needs to be flushed to disk as an sstable. Rather than creating such a large batch, I'd suggest you take a look at [DB.Ingest](https://pkg.go.dev/github.com/cockroachdb/pebble#DB.Ingest). Using `DB.Ingest` you can atomically ingest one or more sstables into the DB. If you have to ingest a very large amount of data, this is much faster than writing a batch.

**Comment by asdine** [comment]
Sorry, by "rollbackable" I meant being able to just throw away the batch in case it's not needed anymore.

I'm trying to implement arbitrarily large SQL transactions on top of Pebble Batches. Here's an example that illustrate what I would like to do:

```sql
INSERT INTO foo (a) VALUES (1), (2) --, ... 1M rows

BEGIN; -- db.NewIndexedBatch()

CREATE INDEX foo_a_idx ON foo(a); -- batch.Set() x 1M

UPDATE foo SET a = 1 WHERE a % 2 = 0; -- batch.Set() x 500k

DELETE FROM foo WHERE a < 500000; -- batch.Delete() x 500k

SELECT * FROM foo; -- batch.NewIter() -> 500k results

ROLLBACK; -- throw away the batch, COMMIT is also an option

SELECT * FROM foo; -- -> 1M results
```

No MVCC, one writer at a time.

This would require a WAL to store the large number of changes before the commit. I initially thought that Pebble Batches were being written to the WAL prior being committed, but then I realized they were kept in memory, which probably means that they are not designed for this use case.

> the batch needs to be written to the WAL (and writing a 4+ GB batch will be slow), and the batch needs to be flushed to disk as an sstable

Is there an API in Pebble for that or does that mean that I should implement a separate WAL? 

> Rather than creating such a large batch, I'd suggest you take a look at DB.Ingest.

Is this still a good option for this use case?

**Comment by petermattis** [comment]
If you only have 1 writer at a time, using `DB.Ingest` might be feasible, though you're going to have some complexity as you need to be able to read the uncommitted writes from within that uncommitted txn. RocksDB's [WritePrepared](http://rocksdb.org/blog/2017/12/19/write-prepared-txn.html) suggest another way forward, though one that would require deep changes to Pebble (for which you'd have to fork Pebble). 

> > the batch needs to be written to the WAL (and writing a 4+ GB batch will be slow), and the batch needs to be flushed to disk as an sstable
>
> Is there an API in Pebble for that or does that mean that I should implement a separate WAL?

A batch is written to the WAL as part of it being committed. And a batch is flushed to disk as an sstable after being committed. There is no additional API. The underlying structure of Pebble's WAL is exposed by [record.LogWriter](https://github.com/cockroachdb/pebble/blob/master/record/log_writer.go#L290). There is no access to Pebble's WAL, but this a `LogWriter` would allow you to implement your own separate WAL. 

> > Rather than creating such a large batch, I'd suggest you take a look at DB.Ingest.
>
> Is this still a good option for this use case?

Hard to say definitively, but worth looking at if you only have 1 writer and need to ingest an arbitrarily large amount of data. One bit to be aware of though is that `DB.Ingest` will be slower than using a batch for a small amount of data. I don't know where the crossover point will be.

**Comment by asdine** [comment]
WritePrepared seems perfect for my use case indeed, but maintaining a fork is not in my plans unfortunately.
However `record.LogWriter` and `recordReader` seem to be a great starting point to implementing my own WAL.
Thanks!
