### ISSUE TITLE
How to count the entries in the database?

### ISSUE THREAD

**Issue by temuera** [cockroachdb/pebble#1510]
hi all.
How to count the entries in the database?
What is the best practice?

**Comment by jbowens** [comment]
Hi @temuera — Do you mean counting logical keys (the number of valid keys that you'd observe while scanning the entire database) or counting the number of internal entries, including deletes, overwritten keys, etc?

There is no fast path for counting logical keys. Pebble maintains sstable properties containing the counts of various internal entries, but since keys may delete or shadow each other across levels of the LSM, there's no way of aggregating them.

If you need something more efficient, you could maintain a count of the entries within the database itself, using the merge operator. Your application would need to write to the count key with every batch and avoid blind writes to accurately count deletes and shadowing.

**Comment by jbowens** [comment]
Closing this out, but feel free to reply back if you have additional questions!
