### ISSUE TITLE
Need information on few points about pebbles

### ISSUE THREAD

**Issue by crbsram** [cockroachdb/pebble#1525]
Hi Team
Need to know whether pebble can support TB of data in the data store?
And retrieve more than 300k values for a specific hash key?
Unlike badgerdb whether pebble also encode the values while setting in DB? (because i don't see that explicitly)

Thanks
C.R.Bala

**Comment by nicktrav** [comment]
> Need to know whether pebble can support TB of data in the data store?

This should not be a problem. For use in a distributed context (e.g. CockroachDB), multiple TB of logical data per node is not uncommon (see [here](https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#node-density-testing-configuration)). That said, it will depend on your workload. As Pebble is an LSM-style KV store, multiple copies of the same key and value can exist at multiple levels until redundant copies are compacted.

> And retrieve more than 300k values for a specific hash key?

Pebble currently stores key-value pairs together on disk in an encoded format. If you are mapping your application's "hash key" to a single pebble Key, then it sounds like those 300k application layer value would also be encoded to the Pebble value associated with the hash-key. That sounds potentially problematic, but we'd have to know more about the workload - is it possible to split the values for a hash key at the Pebble layer, etc.

> Unlike badgerdb whether pebble also encode the values while setting in DB? (because i don't see that explicitly)

Can you clarify what you mean here?

**Comment by vishaljangid1729** [comment]
In badgerDB, we have billions of keys of type `string` and values of type `HashValueList`. In our use case length of `HashValueList` might be in millions. We have to encode key and value in `[]byte` before inserting into BadgerDb; we are using the `encoding/gob` package. So, whenever we need values, we have to decode them again. This decoding process is causing overhead in our case. 

Is there any better solution in pebble to mitigate this issue and get high read throughput from DB? 
```
type HashValue struct {
    Row_id  string
    Address string
}

type HashValueList []HashValue

func (v *HashValueList) Encode() []byte {
	var a bytes.Buffer
	enc := gob.NewEncoder(&a)
	err := enc.Encode(*v)
	if err != nil {
		panic(err)
	}
	return a.Bytes()
}

func Decode(arr []byte) HashValueList {
	a := bytes.NewBuffer(arr)
	var list HashValueList
	dec := gob.NewDecoder(a)
	err := dec.Decode(&list)

	if err != nil {
		panic(err)
	}
	return list
}

```

**Comment by nicktrav** [comment]
While we don't have native support for keys with collections of values, you could probably build something on top of Pebble that does what you want using "prefix iteration". Note that this would have to be built out in your application layer.

With prefix iteration, you would store each of the values from your collection as a distinct Pebble KV pair, rather than a single key with a large value. The _prefix_ of the key would be the original hash value key. You'd then need to add a suffix to provide uniqueness over the collection of values from the original collection. The encoding scheme would be up to you to define.

So in your original scheme, where you have something like:

```
k1 -> [v1, v2, v3, ..., vn]
...
km -> [w1, ..., wm]
```

You would now have something like:

```
k1@1 -> v1
k1@2 -> v2
k1@3 -> v2
...
k1@n -> vn
...
km@1 -> w1
...
km@m -> wm
```

In this prefixed layout, you need to provide a [split function](https://github.com/cockroachdb/pebble/blob/13f8f7cee6ef3c8724a2c1c99a2cfff034e8b638/internal/base/comparer.go#L69-L102) to the DB that provides a means of splitting a key into a prefix and suffix. At iteration time, you can look up your hash key using [`SeekPrefixGE`](https://github.com/cockroachdb/pebble/blob/13f8f7cee6ef3c8724a2c1c99a2cfff034e8b638/iterator.go#L926-L969), and then continue to iterate until you see the next prefix.

This would save you needing to deserialize _all_ the values in the collection just to fetch a single value, for example. The obvious downside is that you need to build this out yourself on top of Pebble - inserts / updates / deletes of collection values would be specific to your application (e.g. what do you use as the suffix; how do you order the collection values; how do you remove a collection value, etc.). 

CockroachDB uses prefixes heavily, specifically for MVCC (user keys can have multiple "versions" each with their own value), and there are various optimizations that have been implemented for this prefix-iteration mode.

Hope this helps!

**Comment by crbsram** [comment]
Thanks
This really helps a lot. And Moreover this seems to make sense.

We will write some quick code to check the response timings.

Thanks
C.R.Bala

**Comment by crbsram** [comment]
--Update--
After implementing with workaround we are struck in calloc function called from the library ristretto within badger db.
We are planning to leverage pebble and will run some tests on this front. We shall come-back with some stats.
We will be happy if pebbles works in our usecase.

Thanks
C.R.Bala

**Comment by nicktrav** [comment]
@crbsram - did you get the answer you were looking for here?

**Comment by jbowens** [comment]
Closing out as inactive, but feel free to bump if you still have questions.
