### ISSUE TITLE
cache: memory for pooled cache `entry` items is leaked when using cgo for allocations

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/pebble#1588]
Currently, when setting an entry in a cache shard via `Set()`, [an `entry` is pulled from a pool of  `entryAllocCache`s](https://github.com/cockroachdb/pebble/blob/0ad186894f6dfa60b3b39371fa6df2d623f4dfd7/internal/cache/entry_normal.go#L37-L42), each containing a slice of `entry` structs, each of which is backed by memory allocated via `manual.New`. When freeing an `entry`, an `entryAllocCache` is pulled from the pool, and the entry is is placed in `[]entry` slice for later use (or the memory backing the `entry` is released if the slice is full). 

The `entryAllocPool` constructs new `entryAllocCache` structs via `newEntryAllocCache`, which, when running with cgo enabled [sets a finalizer on the new `entryAllocCache`](https://github.com/cockroachdb/pebble/blob/0ad186894f6dfa60b3b39371fa6df2d623f4dfd7/internal/cache/entry_normal.go#L56-L60) that is intended to deallocate the memory backing each of the `entry` structs in the slice when the Go runtime GC's the `entryAllocCache`.

However, [the finalizer is a no-op when the following is true `(!invariants && !tracing) || race`](https://github.com/cockroachdb/pebble/blob/0ad186894f6dfa60b3b39371fa6df2d623f4dfd7/internal/invariants/finalizer_off.go#L10-L14). For production builds (i.e. Cockroach builds), neither `invariants` nor `tracing` is enabled, so the first predicate evaluates to true, installing the no-op finalizer. As the backing memory for the `entry` items is _not_ released, and this can result in a memory leak.

Experimenting with `pebble bench write` revealed ~1MB leaked over a ten minute period, when running with a load of 10k sets / sec. The amount leaked is not deterministic given that the leak only occurs whenever the pooled `entryAllocCache` items are GC'd, but is always a multiple of [`96` (the size of the `entry` struct)](https://github.com/cockroachdb/pebble/blob/0ad186894f6dfa60b3b39371fa6df2d623f4dfd7/internal/cache/entry_normal.go#L19).

**Comment by bananabrick** [comment]
I don't think there exists a method to execute some code when an item in the pool gets gcd, other than the finalizer method which we seem to be using.

It seems like the purpose of the pooled `entryAllocCache` to ensure higher concurrency on calls to `entryAllocNew`. I imagine using a single `entryAllocCache` would require us to implement synchronization mechanisms.

If we want to keep using a `sync.Pool` here, could we prevent objects in sync.Pool from being gc'd by holding references to them. This isn't a great solution because it will increase memory usage, but will prevent the memory leak.

Using a sync.Pool to fetch and retrieve the `entryAllocCache` seems inadequate for our purposes, since we're manually allocating the memory which needs to be put in the pool.

From our `docs/memory.md`:

```
## Leak Detection

In order to find all of the cache value leaks, Pebble has a leak
detection facility built on top of
[`runtime.SetFinalizer`](https://golang.org/pkg/runtime/#SetFinalizer). A
finalizer is a function associated with an object which is run when
the object is no longer reachable. On the surface, this sounds perfect
as a facility for performing all memory reclamation. Unfortunately,
finalizers are generally frowned upon by the Go implementors, and come
with very loose guarantees:

> The finalizer is scheduled to run at some arbitrary time after the
> program can no longer reach the object to which obj points. There is
> no guarantee that finalizers will run before a program exits, so
> typically they are useful only for releasing non-memory resources
> associated with an object during a long-running program

This language is somewhat frightening, but in practice finalizers are
run at the end of every GC period. Pebble does not use finalizers for
correctness, but instead uses them for its leak detection facility. In
the block cache, a finalizer is associated with the Go allocated
`cache.Value` object. When the finalizer is run, it checks that the
buffer backing the `cache.Value` has been freed. This leak detection
facility is enabled by the `"invariants"` build tag which is enabled
by the Pebble unit tests.
```

Since this states that we shouldn't be relying on finalizers to free memory, we could also roll a custom cache for the manually allocated entries.

**Comment by nicktrav** [comment]
Yeah - pool plus manual memory management without a finalizer feels like an oversight. Looks like the tags got added to work around some test failures in Cockroach (#729).

For what it’s worth, using the regular finalizer eliminated this leak completely, but per the doc you linked, we probably don’t want to rely on just the finalizer.

Custom free list might another option.

**Comment by petermattis** [comment]
@nicktrav This looks like a major head slapper on my part. Can you look through the history of how this code evolved? I'm pretty sure this worked correctly originally, and then we had problems with finalizers in race builds so we stopped using them ~everywhere, including in this usage where they were in fact necessary. I believe it may be ok to use finalizers in this usage. I think that may have been my intention with the `entriesGoAllocated` conditional which is only true in race builds or if cgo is disabled. So the problem may be using `invariants.SetFinalizer` rather than `runtime.SetFinalizer`.

**Comment by nicktrav** [comment]
For the eventual backports of this, it looks like the leak is present in Cockroach versions [21.1.x](https://github.com/cockroachdb/pebble/blob/74c112a0ac85/internal/cache/entry_normal.go#L58) and [21.2.x](https://github.com/cockroachdb/pebble/blob/fe22683f9088/internal/cache/entry_normal.go#L58).

**Comment by petermattis** [comment]
> I did some Git archaeology ...

Thanks for doing this. And nice job tracking down this leak in the first place.

> Yep, I agree with this assessment. I think it's fine to keep using the finalizer here - however in the spirit of the comment that Arjun linked, we'll probably want to update it to mention that we are indeed now using the finalizer for correctness, as without it, we leak memory.

SGTM
