### ISSUE TITLE
metamorphic: failure from 5/12

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/pebble#1696]
Found via a metamorphic test run ([logs](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_Pebble_Metamorphic/5148979?buildTab=log&focusLine=4970&linesState=4640)).

```console
===== SEED =====
1652328614327314275
===== DIFF =====
/artifacts/meta/220512-041014.327/{standard-000,random-014}
@@ -2836,11 +2836,11 @@
 iter20.SetBounds("xwtvnf@5", "xwtvnf@5") // <nil> #2836
 iter20.SeekLT("xwtvnf@5", "") // [false] <nil> #2837
 iter20.Next("") // [false] <nil> #2838
 iter20.Next("") // [false] <nil> #2839
 db.Checkpoint() // <nil> #2840
-iter22.SeekLT("tcyaakitgrc@3", "") // [true,"tbvrm",<no point>,["tbvrm","thxhtpuq")=>{"@8"="fgxw"}] <nil> #2841
+iter22.SeekLT("tcyaakitgrc@3", "") // [true,"tbvrm",<no point>,["tbvrm","thxhtpuq")=>{"@8"="fgxw","@6"="iaqxeeazwsbmgww","@5"="yzogvpcbl"}] <nil> #2841
 db.Delete("cntsza@3") // <nil> #2842
 iter22.Close() // <nil> #2843
 db.Ingest(batch17) // <nil> #2844
 db.SingleDelete("atnoyhosgne@1", false /* maybeReplaceDelete */) // <nil> #2845
 snap17.Get("fqotynytfcm@1") // [""] pebble: not found #2846
```

SHA: `f8897076324b `.

_NOTE: I filled this in manually, as we didn't get an automated issue._

**Comment by nicktrav** [comment]
cc: @jbowens - this looks range key related, based on the diff.

**Comment by jbowens** [comment]
This is one was fixed by the revamp of iterator indexed batch semantics in #1640.

```
(tbvrm-tbzodyemxv:{
    (#36028797018964071,RANGEKEYSET,@8,fgxw)
    (#738,RANGEKEYDEL)
    (#592,RANGEKEYSET,@6,iaqxeeazwsbmgww)
    (#542,RANGEKEYSET,@6,tbwpmnahyjktxmugcd)
    (#529,RANGEKEYUNSET,@7)
    ...
})
```

The iterator with inconsistent results (`iter22`) is created at sequence number `#738`, just before the call to `RangeKeyDelete('tbvrm', 'tbzodyemxv')` so it must not observe the delete. However, `iter22` is an iterator reading through an indexed batch. The indexed batch contains a `RANGEKEYSET` (observed above at sequence number `#36028797018964071`). This `RANGEKEYSET` tickled the bug in `Span.Visible`, causing this `RANGEKEYDEL` to almost always be observable. However, with the options of `random-014`, we'd sometimes get a WAL & memtable rotation right between the Iterator construction and the `RangeKeyDelete`:
```
iter22 = batch17.NewIter("", "", 0 /* key types */, "" /* masking suffix */) // <nil> #2805
// INFO: [JOB 232] WAL created 000170
db.RangeKeyDelete("tbceir", "xmxyzhagbjy") // <nil> #2806
```
When timed like above, the memtable rollover caused the `RANGEKEYDEL` to be written to a new memtable that `iter22` wouldn't read, causing the run to correctly not observe the `RANGEKEYDEL`.
