### ISSUE TITLE
curious about the size of the example 1 key value size.

### ISSUE THREAD

**Issue by hiqsociety** [cockroachdb/pebble#1770]
why does the whole directory of the db of 1 key value <1024bytes, shown 4.5mb but individual files are lesser than 2kb? what's the rationale for this? in actual detail, is it 2kb or 4.5mb size? 

```
drwxr-xr-x 2 root root  137 Jun 16 13:26 .
drwxr-xr-x 3 root root   70 Jun 16 10:37 ..
-rw-r--r-- 1 root root  779 Jun 16 10:35 000004.sst
-rw-r--r-- 1 root root   47 Jun 16 13:26 000008.log
-rw-r--r-- 1 root root   16 Jun 16 13:26 CURRENT
-rw-r--r-- 1 root root    0 Jun 16 13:26 LOCK
-rw-r--r-- 1 root root   97 Jun 16 10:35 MANIFEST-000006
-rw-r--r-- 1 root root   97 Jun 16 13:26 MANIFEST-000009
-rw-r--r-- 1 root root 1120 Jun 16 13:26 OPTIONS-000010
# du -h --max-depth=1
4.5M    .
```

**Comment by jbowens** [comment]
Hi @hiqsociety,

`ls` reports the _apparent size_ (or logical size) of the file. For all of these files, the logical size is the number of bytes Pebble actually wrote to the file. `du` computes actual disk usage, which takes into account block sizes. If you write a single byte to a file, the filesystem needs to still allocate a whole block for the file.

I believe you can run `du -h *` to print the actual disk usage of each of these files. Additionally, the directory itself consumes disk space to store all the directory entries.

**Comment by hiqsociety** [comment]
wow! 4.5M for        
        key := []byte("hello")
        if err := db.Set(key, []byte("world"), pebble.Sync); err != nil {
                log.Fatal(err)
        }

anyone knows how to have the bare minimum settings to ensure pebble is using as minimal / tiny space as possible? i would like to use it to create multiple dbs for users but those users may not be active.

```
# du -h *
1.0K    000004.sst
4.5M    000008.log
1.0K    CURRENT
0       LOCK
1.0K    MANIFEST-000006
1.0K    MANIFEST-000009
2.0K    OPTIONS-000010
```

**Comment by jbowens** [comment]
The majority of the disk space there is consumed by the WAL file. Pebble preallocates WAL files for performance, which is why a near-empty WAL file appears to be `4.5 M`. The preallocated size of this WAL file corresponds to the size of the current memtable, so this may grow up to `Options.MemTableSize`. I don't think there's currently a way disable preallocation. Adding an option to disable it is straightforward, but it would be nice to avoid supporting too many fine-grained configuration options.

>  i would like to use it to create multiple dbs for users but those users may not be active.

Will you be opening and closing the databases, or keeping all of them open? I think you would likely find it more performant to use a single database, partitioning your keyspace by user.
