### ISSUE TITLE
db: `RangeKeyChanged()` not firing when seeking reused prefix iterator

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/pebble#1886]
See https://github.com/cockroachdb/cockroach/pull/86111#issuecomment-1214471988.

**Comment by jbowens** [comment]
@erikgrinaker I haven't produced this particular failure yet, but I think it probably points to some general iterator interface complications with reuse. Specifically, seek operations don't set `RangeKeyChanged()=true` if the seek finds seeks to the same range key. `SeekPrefixGE` doesn't set `RangeKeyChanged()=true` unless seeking to a different prefix (which always results in changed `RangeKeyBounds()`). Is this the case we're hitting in BenchmarkMVCCGet?

We unconditionally call `SetOptions` when reusing an iterator, right? I think maybe `SetOptions` should clear state so that a subsequent seek to an identical range key returns `RangeKeyChanged()=true`.

**Comment by jbowens** [comment]
Looks like #1888 fixes the BenchmarkMVCCGet benchmark

**Comment by erikgrinaker** [comment]
I'm not sure that's the whole story -- either the iterator must have been invalidated, and not triggered RangeKeyChanged after a seek (which it should), or the iterator must've been valid before the seek but not surfaced the range key in HasPointAndRange.
