### ISSUE TITLE
sstable: deprecate and remove table property collectors/filters

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/pebble#1887]
Table properties are obsoleted by block properties. Cockroach stopped using table properties in 22.2, and the minimum Pebble format major version was bumped to a version high enough to guarantee block properties are available (cockroachdb/cockroach#82678).

Remove the obsolete table properties code.

**Comment by RaduBerinde** [comment]
I believe the relevant version is [FormatPrePebblev1MarkedCompacted](https://github.com/cockroachdb/pebble/blob/master/format_major_version.go#L155C2-L155C34). But this is listed as a 23.2 version. So we will only be able to remove this code once we break compatibility with 23.1. Note that 24.1 will allow upgrading directly from 23.1 as an experimental feature. @jbowens is my assessment correct?

**Comment by jbowens** [comment]
I think this case is a little more relaxed, because the presence of these properties is not required for correctness. They're an optimization for time-bound iteration. We won't have a _guarantee_ that the same data is encoded into block properties for all sstables until `FormatPrePebblev1MarkedCompacted`. In practice though we started writing the block properties in 22.1, so only sstables that were written in 21.2 or earlier and never compacted since then will be missing equivalent block properties.

If we removed support for reading table properties from 24.1, it would be possible for a cluster upgrading from 23.1 to 24.1 to experience a performance regression in incremental backups, CDC catch up scans, etc until the cluster version finalization ratchets completes the ratcheting to FormatPrePebblev1MarkedCompacted. Since that upgrade flow is considered experimental, I think we should do it.

**Comment by RaduBerinde** [comment]
@nicktrav @jbowens I can work on this now that we deprecated older versions. Could you give me a couple of pointers of what code we want to remove? I assume it's not the entire `sstable.Properties` is it?

**Comment by nicktrav** [comment]
My understanding (hazy) is that we want to remove the `sstable.TablePropertyCollector` interface, and it's implementations. The interface plumbs down into the sstable writer as a field `propCollectors`. I believe that is just accumulating a map and then putting it in `sstable.Properties.UserProperties`.

There's also a read path.

Instead of table properties, we have the more granular block properties. Worth a double check that we have no plans of using the table-level filters. I believe Cockroach has already stopped using them as of a few releases ago.
