### ISSUE TITLE
Context timeout support?

### ISSUE THREAD

**Issue by ivanjaros** [cockroachdb/pebble#1933]
It looks to me like there is no built-in support for context timeout for batches/transactions. Is that correct or am I overlooking something?

**Comment by jbowens** [comment]
Thanks for the question.

To clarify, a batch is not a transaction. A batch only guarantees atomicity: either all its mutations are applied or none. A batch commit does no conflict resolution.

No, there is no facility to respect a context cancellation. I recommend checking for context cancellation before committing, if required.

A batch commit is two things:
1. Copying the batch into the in-memory memtable. This is fast, because it’s just memory copies.
2. Appending the batch to the write ahead log. The actual disk IO here is not cancelable once in progress.

In an overloaded system, there can be additional latency waiting for one’s turn for a chance to commit. To prevent overload, I recommend doing traffic shaping above Pebble where you have knowledge of relative priorities of writes.

**Comment by ivanjaros** [comment]
ok, thought so. thanks.
