### ISSUE TITLE
bench: dump pebble logs after ycsb run

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/pebble#2191]
Currently, after a completed `bench ycsb` run, the pebble logs do not get written to disk for the user to inspect, by default. They should be.

**Comment by bananabrick** [comment]
Redirecting the output of the benchmark to a file has worked well for me.

**Comment by msbutler** [comment]
right, I know I can run `bench ycsb ... > output.txt`, but @itsbilal indicated there was another log channel that would log write stalls, for example, that are not by default captured in the ycsb output.

**Comment by bananabrick** [comment]
I think I've been able to see write stalls. Maybe try redirecting stderr as well.

**Comment by msbutler** [comment]
hm, maybe I'm misunderstanding something. I'll let @itsbilal comment.

**Comment by itsbilal** [comment]
I was just looking over @msbutler's screen and only saw the summary at the end, no compaction lines above it so I figured we didn't put the write stall lines in the stdout/stderr. And a quick code inspection (where I missed a key detail) didn't show me where we set the logger in `runTest`. But turns out we do, so yes we can close this issue. Sorry for the misleading trek!

@msbutler you should see "write stall" lines in stdout then with your higher-concurrency run, let me know if you don't. As well as lots of `flushing:` and `compacting` lines.
