### ISSUE TITLE
db: allow ingesting into the lowest level which doesn't overlap ingested sstable

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#221]
`ingestOverlap` finds the lowest level in the LSM which does not have an sstable which overlaps the sstable being ingested. This is done via checks of the sstable boundaries. RocksDB does something slightly more sophisticated in [`Version::OverlapWithLevelIterator`](https://github.com/facebook/rocksdb/blob/master/db/version_set.cc#L1514-L1571). It creates a level iterator, then seeks to the start key of the sstable being ingested and checks to see if there is a key in the level which overlaps with the boundaries of the ingested sstable. This allows RocksDB to ingest into lower levels in some cases. Are those cases important? That isn't clear. Implementing the RocksDB heuristics would not be difficult, though.

Hat tip to @ajkr for pointing out this RocksDB functionality.

**Comment by ajkr** [comment]
@rohansuri continuing our discussion on #465 here.

>It'd help if you could explain Peter's comment:
"This allows RocksDB to ingest into lower levels in some cases".
>
> What are these cases?

Consider the following LSM.

```
L0_1: ab-----------------------z
L0_0:    d--------------s
L1:   c----h j--m--p  s-----y
```

I am not sure how much background you have in leveldb-style LSMs. Please ignore the extra detail if it's unnecessary.

To make sure the drawing above is clear, let me explain a couple of the files.

* The file L0_1 has smallest key "a" and largest key "z". It contains the point keys "a", "b", and "z".
* The second L1 file has smallest key "j" and largest key "q". It contains the point keys "j", "m", and "p".

There are two L0 files: L0_1 and L0_0. L0_1 is the newer one. As you can see L0 files can overlap in the keyspace. This happens because each L0 file is created by flushing a whole memtable, which contains all keys written since the previous flush.

In L1 there are three files. L1 and all "lower" levels, which confusingly have higher level numbers, e.g., L2 is lower than L1, are guaranteed to not overlap in the keyspace. This can be guaranteed because, unlike flush, compaction pulls in overlapping data from that level and rewrites it whenever compacting into a L1+ level.

Now, back to ingestion. Say we are ingesting a file with two keys, "q" and "r". Cockroach attempts to ingest files covering narrow portions of the keyspace to minimize overlap, so it is reasonable to consider such a narrow file as our example. As of today, it'll be ingested to create an LSM like this:

```
L0_2:                 qr
L0_1: ab-----------------------z
L0_0:    d--------------s
L1:   c----h j--m-o    t----y
```

Since `qr` overlaps with L0_1 according to their boundary keys, today we conclude that the ingested file is newer than L0_1 and ingest it accordingly. But actually there's no harm to ingest it into L1. Although `qr`'s boundaries overlap with the boundaries of L0_1 and L0_0, their keys do not actually overlap. RocksDB follows a pattern like this to determine whether keys overlap (ignoring range deletions for now):

* `SeekGE("q")` in L0_1. If the key returned is nil or greater than "r", the keys in L0_1 do not overlap, so it can be ingested beneath L0_1.
* `SeekGE("q")` in L0_0. If the key returned is nil or greater than "r", the keys in L0_0 do not overlap, so it can be ingested beneath L0_0.
* Now it knows the file can be ingested into L1 assuming there's a fit. To actually fit it in a level (i.e., not just conclude it can be ingested beneath a level), it must not have overlapping boundaries with existing files. The file fits between `j--m-o` and `t----y` so it can be ingested to produce the following more compact LSM.

```
L0_1: ab-----------------------z
L0_0:    d--------------s
L1:   c----h j--m-o qr t----y
```

**Comment by rohansuri** [comment]
Thanks for the explanation @ajkr. I have more clarity now and understand RocksDB's heuristic.

Correct me if I'm wrong but the *ideal* ingestion decision for L0 should be the following:
To maintain the constraint that for a given key higher levels will have larger sequence numbers than lower levels, *if* L0 contains *any* of the point keys from the ingested file, then to obey the constraint we cannot go further down since keys in ingested file will have higher sequence number than keys in L0. 

For example, current LSM:
```
L0_0: ab--------------r-----------z
L1:     c----h j--m-o    t----y
```
Ingested file contains keys "q", "s".
Ingestion into L1 is still possible since L0 does not container either of "q" or "s".

However with RocksDB's heuristic we'd ingest into L0 because `SeekGE("q")` finds "r" in L0_0, which is lesser than "s" hence considering it an overlap.

But this is not done in practise because it is expensive since it involves iterating over *each* of the keys in ingested file and finding it in L0.

---

Coming back to using RocksDB's heuristic of using `SeekGE`, isn't it only required for L0? For all lower levels we can still use the boundaries as we now do because only the lower levels have an additional constraint of being non-overlapping.

As for making this behaviour change, I expect we'd do it inside [`ingestTargetLevel`](https://github.com/cockroachdb/pebble/blob/master/ingest.go#L297) rather than changing the behaviour of `Version.Overlaps` which is used at multiple places and has it's behaviour documented.

I'll gather some thoughts on how range deletions affect the scenario and let you know soon, after which I can start implementing the solution.

**Comment by ajkr** [comment]
> Correct me if I'm wrong but the ideal ingestion decision for L0 should be the following:
> To maintain the constraint that for a given key higher levels will have larger sequence numbers than lower levels, if L0 contains any of the point keys from the ingested file, then to obey the constraint we cannot go further down since keys in ingested file will have higher sequence number than keys in L0.

Agreed, it could be ingested into L1 in even more cases if we were willing to check for overlap of every key. I'd also think this is not done due to performance concerns.

> Coming back to using RocksDB's heuristic of using SeekGE, isn't it only required for L0? For all lower levels we can still use the boundaries as we now do because only the lower levels have an additional constraint of being non-overlapping.

We could use the file boundaries to check overlap at L1+ (as we do today), but there are opportunities to ingest beneath overlapping files in L1+. For example, consider ingesting `qr` into this LSM.

```
L1:   a--------j l------s u----z
L2:     c----h j--m-o    t----y
```

Although `qr` overlaps with `l------s` in its boundaries, `SeekGE("q")` on an L1 iterator returns "s", which tells us we are allowed to ingest beneath L1. I think we could do something like this at each level.

* First check whether file boundaries overlap. If no overlap, then we can ingest either at this level or beneath this level.
* Otherwise, use `SeekGE()` on the ingested file's start key. If it lands beyond the ingested file's end key, then we can ingest beneath this level only.
*  Otherwise, we cannot ingest at or beneath this level. Return the lowest level we found that we can ingest at.

**Comment by rohansuri** [comment]
@ajkr took some time to understand the range deletion intricacies and iterator implementations (the tests under [range_del_test.go](https://github.com/cockroachdb/pebble/blob/master/range_del_test.go) are interesting). 

Yes you are right. The constraint "for a given key higher levels will have larger sequence numbers than lower levels" applies for all levels.

So at each level there are two questions to answer:
1. Can I ingest the file in this level? 
We always can in L0. However for L1 and below we must be non-overlapping with the sst boundaries.

2. Does an overlap with point keys or range tombstones of the ssts on this level stop me from going further down?
This is to obey the seqnum constraint. 
It requires finding an overlapping sst (same binary search as in [levelIter.findFileGE](https://github.com/cockroachdb/pebble/blob/master/level_iter.go#L181)) and then seek through it's point keys, range tombstones using `DB.newIters` to check for overlap (similar to [`ingestMemtableOverlaps`](https://github.com/cockroachdb/pebble/blob/master/ingest.go#L255)).
We could also use `levelIter` directly and it's `SeekGE` for checking point key overlaps and then initialize a rangeDelIter using `levelIter.index` and `DB.newIters` after landing on the target file.
Do you have any preference in the way of doing iteration?

Question regarding the checks in `ingestMemtableOverlaps`:
For the point key [comparison](https://github.com/cockroachdb/pebble/blob/master/ingest.go#L266), shouldn't we check for range delete sentinels and not consider them as overlapping?
```go
if cmp(key.UserKey, m.Largest.UserKey) < 0 ||
   (cmp(key.UserKey, m.Largest.UserKey) == 0 && m.Largest.Trailer != InternalKeyRangeDeleteSentinel) {
   return true
}
```
Similarly for the range delete [checks](https://github.com/cockroachdb/pebble/blob/master/ingest.go#L281), 
```go
c := cmp(key.UserKey, meta.Largest.UserKey)

if c > 0 || (c == 0 && meta.Largest.Trailer == InternalKeyRangeDeleteSentinel) {
// The start of the tombstone is after the largest key in the
// ingested table.
   break
}
```

Let me come up with a draft WIP PR to get some early feedback.

**Comment by petermattis** [comment]
> The constraint "for a given key higher levels will have larger sequence numbers than lower levels" applies for all levels.

Note that this constraint is also captured and verified by `DB.CheckLevels`.

> Question regarding the checks in ingestMemtableOverlaps:
For the point key comparison, shouldn't we check for range delete sentinels and not consider them as overlapping?

Range deletion sentinels never occur in memtables. The sentinel is only generated as the boundary key for sstables. If you're iterating over the range tombstones for an sstable, you will also not see the range deletion sentinel.

**Comment by rohansuri** [comment]
> Note that this constraint is also captured and verified by DB.CheckLevels

This is helpful. I've added it at the end of the ingestion test to verify constraints are satisfied.

> Range deletion sentinels never occur in memtables. The sentinel is only generated as the boundary key for sstables. If you're iterating over the range tombstones for an sstable, you will also not see the range deletion sentinel.

Got it. I think my comment is still relevant because the checks I suggested were based on the sst boundaries. For example [this](https://github.com/cockroachdb/pebble/pull/511/files#diff-355a701c86c7182839275accc4d356b7R396) test case.
