### ISSUE TITLE
internal/manifest: equivalence of incremental and non-incremental sublevels creation

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#2475]
There are two means through which L0 sublevels are created. One takes all of L0 files and builds the sublevels from scratch. The other builds off the existing sublevels incrementally. We should make these two methods always construct identical sublevels and add assertion invariants to the effect.

**Comment by RaduBerinde** [comment]
I believe they are already intended to construct identical sublevels, `TestAddL0FilesEquivalence` is a test along those lines.

What is missing is a check for this outside of the unittest - we should periodically reconstruct L0 and check that it doesn't change. This would still be confined to tests because it would be behind the `invariants` tag, but we'd get more coverage through the metamorphic test.
