### ISSUE TITLE
sstable: progress indicator or speed up on 100mb+ ssts

### ISSUE THREAD

**Issue by tbg** [cockroachdb/pebble#2511]
A few colleagues and I are on an escalation right now and were using the `./cockroach debug pebble check` command on the data directory to verify SST integrity. This seemed to hang on one SST (10+ minutes with no output) and we're unsure if it got stuck or if it's simply supposed to take that long.

The command should either finish in a reasonable amount of time per SST (seconds?) or print a progress indicator.

**Comment by jbowens** [comment]
This was the borked machine that presumably had a defective CPU, right? If so, I think that could reasonably cause an infinite loop where one is otherwise impossible.

**Comment by jbowens** [comment]
We talked about this during triage and even a 128 MB L6 sstable should only take a couple seconds. It seems likely that the unidentified hardware issue caused this command to hang for 10 minutes. IIRC, `cockroach debug pebble sstable check` _does_ print each file as it progresses through the arguments. Since each individual sstable should never take more than a couple seconds, do you still think we need a progress indicator for this command?

**Comment by jbowens** [comment]
@tbg closing this out, but feel free to reopen.
