### ISSUE TITLE
vfs/default_linux_arm.go:21:21: undefined: isSyncRangeSupported

### ISSUE THREAD

**Issue by rv888** [cockroachdb/pebble#2514]
Appears the necessary functions are not in default_linux_arm.go but I do see them in default_linux_noarm.go

**Comment by jbowens** [comment]
Thanks, I think there's something to fix here. It's unclear if we should be calling `isSyncRangeSupported` at all (because it's not provided on arm under any case), or we should update the logic (and possibly unify `!arm` and `arm` cases) to appropriately handle the sync range support detection.

Related to #171.
