### ISSUE TITLE
github.com/cockroachdb/pebble/internal/metamorphic: TestMeta failed

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/pebble#2562]
[Seen here.](https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=10217641&_focus=107639)

Trace:

```
===== SEED =====
1684902326168487385
===== ERR =====
exit status 2
===== OUT =====
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x180 pc=0x986cbc]

goroutine 43 [running]:
github.com/cockroachdb/pebble.(*DB).FormatMajorVersion(0xc00049dba0?)
	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/format_major_version.go:373 +0x3c
github.com/cockroachdb/pebble/metamorphic.(*test).isFMV(...)
	github.com/cockroachdb/pebble/metamorphic/external/com_github_cockroachdb_pebble/metamorphic/test.go:178
github.com/cockroachdb/pebble/metamorphic.(*deleteOp).run(0xc0003c4320, 0xc0000fc2a0, {0xc0003c4480?, 0x0?})
	github.com/cockroachdb/pebble/metamorphic/external/com_github_cockroachdb_pebble/metamorphic/ops.go:195 +0x6b
github.com/cockroachdb/pebble/metamorphic.RunOnce.func1()
	github.com/cockroachdb/pebble/metamorphic/external/com_github_cockroachdb_pebble/metamorphic/meta.go:498 +0x179
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:72 +0xa5
```

Repro:

```
$ go test -tags 'invariants' -exec 'stress -p 1' -timeout 0 -test.v -run TestMeta$ ./internal/metamorphic -seed 1684902326168487385 -ops "uniform:5000-10000"
```

**Comment by nicktrav** [comment]
As part of this investigation, we should see why we didn't get a GH issue for this.

**Comment by nicktrav** [comment]
@bananabrick - assigning to you as L2.

**Comment by jbowens** [comment]
looks like I probably introduced this with my `DeleteSized` PR (that introduced that `isFMV` function).

**Comment by bananabrick** [comment]
Flushing some findings. Pretty easy to reproduce.

1. Read through the metamorphic test changes in the `DeleteSized` pr and nothing stands out.
2. `test.db` in the metamorphic test is being set to nil. So, the `t.isFMV` call panics because it accesses the db.
3. I checked that `test.db` is at least set once, and then checked all the references which unset it. None of them are called, except one.
4. `test.db` is set to `nil` during the `closeOp`, of the `objID.tag() == dbTag`. This seems to be happening. Usually, this would be expected, but I think we might be calling `closeOp` on the db earlier than we should because it's being called when the `test.idx == 0`, which unsets `test.db`.

**Comment by itsbilal** [comment]
Another failure if it helps, https://teamcity.cockroachdb.com/viewLog.html?buildId=10236286&buildTypeId=Cockroach_Nightlies_Pebble_Metamorphic

**Comment by jbowens** [comment]
@bananabrick Nice finds! Yeah, that all makes sense to me. I suspect if you _applied_ all the live batches before the db close op, the bug wouldn't happen since batch application synchronizes on the database as well.

I think it would be reasonable to refactor the way `isFMV` works—maybe add an `atomic.Value` to the `test` struct and have `init` plus `dbRatchetFormatMajorVersionOp`s update the `atomic.Value`.

**Comment by bananabrick** [comment]
Didn't get to fixing this today, so this is going to fail again. Will fix tomorrow.
