### ISSUE TITLE
Question about string of (*Options).TargetByteDeletionRate, which is min_deletion_rate

### ISSUE THREAD

**Issue by ijsong** [cockroachdb/pebble#2743]
I understood that TargetByteDeletionRate is an upper limit for the rate of deleting sst files. 

https://github.com/cockroachdb/pebble/blob/7bb765ecf127eb634cc120e445769d686aa31516/options.go#L878-L889

However, the String method of Options uses the term min_deletion_rate. It doesn't seem natural; max_deletion_rate appears proper to indicate the option. Do I misunderstand it?

https://github.com/cockroachdb/pebble/blob/7bb765ecf127eb634cc120e445769d686aa31516/options.go#L1196

**Comment by RaduBerinde** [comment]
Hi @ijsong - the string is historical, this option used to be called `MinDeletionRate`. I agree it was very confusing, which is why I renamed it; but I didn't change the on-disk string representation (for backwards compatibility).

The "minimum" comes from the fact that we don't restrict to that rate when our heuristics decide it's not enough (e.g. running out of space). But I agree with you that under normal circumstances, it really is a "maximum" rate.

**Comment by ijsong** [comment]
@RaduBerinde, I understand it thanks to your explanation. Thank you.
