### ISSUE TITLE
metamorphic: TestMeta failed [duplicate FileBacking present in obsolete list]

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#2947]
```
=== NAME  TestMeta/execution/random-020
    meta.go:218: 
        ===== SEED =====
        1695838611509616000
        ===== ERR =====
        exit status 2
        ===== OUT =====
        --- FAIL: TestMeta (0.60s)
        panic: pebble: duplicate FileBacking present in obsolete list [recovered]
        	panic: pebble: duplicate FileBacking present in obsolete list
        
        goroutine 34 [running]:
        testing.tRunner.func1.2({0x10075bca0, 0x10093eb28})
        	/usr/local/go/src/testing/testing.go:1526 +0x24e
        testing.tRunner.func1()
        	/usr/local/go/src/testing/testing.go:1529 +0x39f
        panic({0x10075bca0, 0x10093eb28})
        	/usr/local/go/src/runtime/panic.go:884 +0x213
        github.com/cockroachdb/pebble.(*versionSet).addObsoleteLocked(0xc00075ec00, {0xc000852e00, 0xf, 0xc000119801?})
        	/Users/jackson/go/src/github.com/cockroachdb/pebble/version_set.go:807 +0x3aa
        github.com/cockroachdb/pebble/internal/manifest.(*Version).UnrefLocked(0xc0002d9b00)
        	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/manifest/version.go:1229 +0x165
        github.com/cockroachdb/pebble.(*EventuallyFileOnlySnapshot).Close(0xc0005c1950)
        	/Users/jackson/go/src/github.com/cockroachdb/pebble/snapshot.go:422 +0x10b
        github.com/cockroachdb/pebble/metamorphic.(*closeOp).run(0xc0004c2bcc, 0xc0001880e0, {0xc0001514e0?, 0xc00001db00?})
        	/Users/jackson/go/src/github.com/cockroachdb/pebble/metamorphic/ops.go:158 +0x1e5
        github.com/cockroachdb/pebble/metamorphic.(*test).step(0xc0001880e0, 0xc0002849c0?)
        	/Users/jackson/go/src/github.com/cockroachdb/pebble/metamorphic/test.go:251 +0x4f
        github.com/cockroachdb/pebble/metamorphic.RunOnce({0x100945b60?, 0xc0002849c0}, {0x305218767, 0x2b}, 0x100da63a0?, {0xc0002aa540, 0x33}, {0xc000292ad0, 0x1, 0x1})
        	/Users/jackson/go/src/github.com/cockroachdb/pebble/metamorphic/meta.go:476 +0x116e
        github.com/cockroachdb/pebble/internal/metamorphic.TestMeta(0x10000ab79?)
        	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/metamorphic/meta_test.go:66 +0x128
 
 ```

**Comment by bananabrick** [comment]
I think the code will work correctly even if we don't maintain this invariant check which failed, because we support trying to delete a deleted file.

That said, I don't know why we're adding a file twice to the obsolete list yet.

**Comment by bananabrick** [comment]
Okay, I see the problem. We have that invariant check, but we don't ensure the invariant.

**Comment by bananabrick** [comment]
We call `unrefFiles` in `Version.Unref`.

```
        in unrefFiles [000180:[vhigluyii@134#661,1-vhigluyii@134#661,1] 000186:[lltvpnnic@128#684,1-mgbkbiadd@138#684,1] 000190:[mgbkbiadd@132#702,1-oycyebi@88#702,1] 000193:[bnke@140#710,1-bnke@138#710,1] 000213:[hvmsyyxv@139#769,1-hvmsyyxv@139#769,1] 000172:[bnke@95#653,1-bnke@95#653,1] 000182:[oarvib@103#664,1-oarvib@103#664,1] 000200:[xexi@142#731,1-xexi@142#731,1]]
        in unrefFiles again [000180:[vhigluyii@134#661,1-vhigluyii@134#661,1] 000186:[lltvpnnic@128#684,1-mgbkbiadd@138#684,1] 000190:[mgbkbiadd@132#702,1-oycyebi@88#702,1] 000193:[bnke@140#710,1-bnke@138#710,1] 000213:[hvmsyyxv@139#769,1-hvmsyyxv@139#769,1] 000172:[bnke@95#653,1-bnke@95#653,1] 000182:[oarvib@103#664,1-oarvib@103#664,1] 000200:[xexi@142#731,1-xexi@142#731,1] 000179:[bjxf@77#644,23-xexi@136#649,1] 000188:[ackkcmg@140#683,1-xexi@28#681,1] 000192:[ackkcmg#691,19-xexi#72057594037927935,21] 000194:[ackkcmg#714,19-vhigluyii@65#716,1] 000199:[bnke#727,21-vhigluyii@123#723,1] 000207:[ackkcmg#746,19-vhigluyii@65#72057594037927935,15] 000208:[jrwhpujsf#766,21-vhigluyii#72057594037927935,20] 000215:[bjxf#774,21-xexi@95#777,1] 000177:[ackkcmg#560,21-bnke@106#0,1] 000183:[bnke@65#0,1-oarvib@115#0,18] 000201:[oarvib@29#0,1-xexi#72057594037927935,21]]
```

The first problem is that we have a level metadata for point and range keys both. So it might be possible that the same file can become obsolete according to both level metadatas when `release` is called. That's not the case in this failure.

The second problem is that we have two virtual sstables `183` and `201` both of which becomes obsolete at the same time. So we end up with the same backing sst `170` added to the obsolete list twice, which is where the invariant check is firing.

**Comment by bananabrick** [comment]
Yea, some code is broken.

```
        unrefing in btree 187 175 0xc000857690
        unrefing in btree 186 186 0xc000857810
        unrefing in btree 202 202 0xc000857c90
        unrefing in btree 185 185 0xc000856790
        unrefing in btree 193 193 0xc000856a90
        unrefing in btree 196 196 0xc000856d90
        unrefing in btree 198 198 0xc000857b10
        unrefing in btree 205 205 0xc000494a90
        unrefing in btree 212 212 0xc000496310
        unrefing in btree 181 181 0xc000857210
        unrefing in btree 203 175 0xc000857e10
```

This printing the filenum, file backing num, and the pointer to the file backing struct. Both 203, and 187 have the same filebacking num of 175, but have different file backing structs `0xc000857e10` `0xc000857690`, which is why the reference counting isn't working out. Virtual sstables with the same backing file must share a file backing struct.

**Comment by bananabrick** [comment]
Maybe I'm printing the addresses incorrectly.

```
        in excise 188 177 0xc000752010
        in excise creating leftFile 203 177 0xc0007be490
        in excise creating rightFile 204 177 0xc0007be610
```

Those are filebacking addresses in excise. They should all be the same, but somehow they're different, which doesn't make sense.

**Comment by bananabrick** [comment]
Other comments were just rambling. Hid them cause they're not irrelevant.

Okay I have some sort of a proof that we were seeing this bug because we were adding too many `CreatedBackingTables` entries to the manifest. Such an entry should only be added when an sstable is first virtualized. This is mentioned as an invariant above `VersionEdit.CreatedBackingTables`.

Note that the excise function will create backing tables and add them to the version edit. But these backing tables should only be added to the version edit, if the sstable being virtualized is NOT virtual. If we're further virtualizing an already virtual sstable, then a backing table entry associated with the file backing will already be present in the manifest as part of an older version edit.

I added some logging to metamorphic test failure to confirm this hypothesis. Logs in reverse chronological order.

Basically we have this backing sstable `178` present twice in `Unref` which causes the panic in this issue.
```
                 backin   real
        in Unref 000178 000188
        in Unref 000187 000187
        in Unref 000203 000203
        in Unref 000193 000193
        in Unref 000197 000197
        in Unref 000199 000199
        in Unref 000206 000206
        in Unref 000213 000213
        in Unref 000184 000184
        in Unref 000178 000204
```

those sstables were present twice, because the `btree.Release` function returned file metadatas for both sstable `204` and sstable `188` both of which have sstable `178` as backing. Note that `188` and `204` are pretty far apart, which means that the virtual sstables `188` and `204` were not created at the same time.

Printing out the `FileBacking` addresses for 188 and 204, we see that these addresses are different.

```
in btree 204 178 0xc0008c7360
in btree 188 178 0xc0008c7200
```

Okay, this means that the virtual sstables have different file backing structs, but the same backing file. This is very wrong. But excise just uses the `FileBacking` associated with the sstable which it is virtualizing, so it shouldn't be wrong.

This led me to believe that there was a restart in the metamorphic test and the manifest replay was incorrect. This was the case.

Manifest replay is incorrect because there are `CreatedBackingTables` entries in two different version edits for the same backing table. This is because the excise function doesn't check whether a file which is being split into virtual sstables was already virtual.

If we have two `CreatedBackingTables` entries for the same backing file, in two separate version edits, then manifest replay will create a `FileBacking` struct for the first occurrence, use that for the virtual sstables which need that `FileBacking`, then create another `FileBacking` struct when the second `CreatedBackingTables` is encountered and use that for the remaining virtual sstable which need that `FileBacking`.

In this way, we can end up with multiple virtual sstables with the same backing file, but different `FileBacking` structs.
