### ISSUE TITLE
Question: the level0 compaction threshold configuration

### ISSUE THREAD

**Issue by rjl493456442** [cockroachdb/pebble#2990]
The default threshold for triggering a level0 compaction is set to 500, namely 1GB data by default.

From the code comments, I can understand it's a tradeoff between the read efficiency(pile up too many files) and level0 compaction performance.  However, even with bloom filter enabled and used, the overhead for checking bloom filters of each level0 file is still non-trivial for each Get.

E.g. in the worst case, there are 500 files, load and check bloom filter 500 times overhead is definitely non-trivial.

Open this ticket just want to post this general question, do you guys have any experiment about reducing this to a smaller number?
Don't want to blindly reduce it, just in case we can have some lessons to learn.

**Comment by jbowens** [comment]
First, some background: Unlike in RocksDB/LevelDB, when there are 500 files in L0 Pebble does _not_ necessarily need to read all 500. Pebble uses a data structure called "sublevels" to organize files in L0 into "sublevels". Only files that are non-overlapping in key bounds can sit within the same sublevel. This blog post goes into some of the details: https://www.cockroachlabs.com/blog/bulk-data-import/

If there are 500 files in L0 but all 500 files are non-overlapping and occupy a single sublevel, then a `Get` only needs to read a single file in L0. If there are 500 files in L0 and they all overlap each other, then there must be 500 sublevels and a `Get` needs to read each one.

There are two important L0 compaction heuristics:

1. The primary one is `L0CompactionThreshold`. This heuristic is a function of the number of sublevels. Pebble calculates a score reflecting the compaction priority of L0 using [`(2*numSublevels)/Options.L0CompactionThreshold`](https://github.com/cockroachdb/pebble/blob/36b3f57b6167eb4e25d29dcb7be976d603f47d51/compaction_picker.go#L1095-L1098C38). A score ≥ 1.0 is sufficient to trigger a compaction out of L0 if no other level's score is higher. This setting defaults to `4`, which means there must be at least 2 sublevels for this heuristic to trigger a compaction. CockroachDB [sets this setting to `2`](https://github.com/cockroachdb/cockroach/blob/77f062ec937b6371e4db4070c5ad2760cb920ab3/pkg/storage/pebble.go#L616-L617) to trigger a compaction even if there's a single sublevel.
2. The secondary one is `L0CompactionFileThreshold`. This heuristic is a function of the number of _files_ in L0. It's computed as [`numFilesInL0 / Options.L0CompactionFileThreshold`](https://github.com/cockroachdb/pebble/blob/36b3f57b6167eb4e25d29dcb7be976d603f47d51/compaction_picker.go#L1116). It's used instead of the `L0CompactionThreshold` score only if it's higher than the score computed in terms of `L0CompactionThreshold`. This is the setting that defaults to 500. It was introduced to patch a gap in `L0CompactionThreshold` where writing keys sequentially to Pebble could create a single L0 sublevel with many non-overlapping files. Eventually, when an overlapping key was finally written to L0, a massive compaction could result.

Generally the sublevel-based `L0CompactionThreshold` heuristic is the heuristic that should bound the cost of `Get` reads. You may want to experiment with lowering the `L0CompactionThreshold` to 2. You may also want to experiment with increasing `BlockSize`s so that the fixed cost of a block cache miss is reduced, and using higher `TargetFileSize`s:
https://github.com/cockroachdb/cockroach/blob/77f062ec937b6371e4db4070c5ad2760cb920ab3/pkg/storage/pebble.go#L660-L668

**Comment by jbowens** [comment]
Closing this out, but I'm still subscribed and will see if you reply.
