### ISSUE TITLE
db: add ability to excise without ingest

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/pebble#3820]
Currently, the only way to do an Excise is to do an `IngestAndExcise`. If we added the ability to do excises without an accompanying ingest, likely a `db.Excise(exciseSpans []KeyRange)` method where all the passed-in spans are excised in one atomic VersionEdit, we can replace more uses of rangedels / rangekeydels in CockroachDB with excises and significantly reduce write-amp.

Ideally this would happen after #2676 is complete. This change also makes it easier to complete https://github.com/cockroachdb/cockroach/issues/128004 .

Jira issue: PEBBLE-231

Epic CRDB-37583

**Comment by jbowens** [comment]
I still find it surprising that we see range deletions so disruptive.

Rather than an explicit `Excise` entry point, we could also perform the excise asynchronously as a part of 'delete-only compactions'. I assume the reason range deletions are still disruptive is that we have partial overlap with existing sstables, forcing sstable rewrite. The delete-only compaction logic could just virtualize these partial overlapping sstables, effectively performing an excise.
