### ISSUE TITLE
Release fix for MIPS32 support

### ISSUE THREAD

**Issue by ajsutton** [cockroachdb/pebble#3846]
Back in October a fix for MIPS 32-bit support was merged in https://github.com/cockroachdb/pebble/pull/3005/commits/2acc384ae0ab158ce8af538834ef2aefe4a883bf but this still isn't included in the latest release. Given this completely breaks the ability to compile for MIPS-32 could this be added into a release soon?

For example it wasn't included in the v1.1.1 release on June 15 some 8 months after the original fix.

Jira issue: PEBBLE-240

**Comment by RaduBerinde** [comment]
Hi, a while ago we deprecated older data formats (including the original RocksDB format) and that will not be part of any `v1.x` release since it breaks compatibility. We haven't cut a `v2` release yet (we need to provide a reasonable way to upgrade the format before upgrade). This explains why 1.x doesn't track master anymore.

I will cut v1.1.2 as v1.1.1 + https://github.com/cockroachdb/pebble/commit/2acc384ae0ab158ce8af538834ef2aefe4a883bf

**Comment by RaduBerinde** [comment]
Hm, wait, that commit https://github.com/cockroachdb/pebble/commit/2acc384ae0ab158ce8af538834ef2aefe4a883bf is not in the repo, and those changes are not on the current master. I couldn't find a PR about it either. @ajsutton please clarify.

**Comment by RaduBerinde** [comment]
Oh, never mind, found it. It was automatically rebased as https://github.com/cockroachdb/pebble/commit/f6cde3fc2fa40f5729acf99320b0534886045fbf

**Comment by RaduBerinde** [comment]
Ok, just cut https://github.com/cockroachdb/pebble/releases/tag/v1.1.2

**Comment by ajsutton** [comment]
Awesome thank you so much.
