### ISSUE TITLE
Missing/corrupted records when using the new internal/cache code

### ISSUE THREAD

**Issue by lni** [cockroachdb/pebble#537]
Hi @petermattis, just saw some missing/corrupted records in my test environment. It can be bisect to b880baba077f45917be1f38961910d6d7438ae2e (internal/cache: move the bulk of allocations off the Go heap). 

In my tests, there are multiple background goroutines doing concurrent write/read. When using revisions more recent than the above mentioned one, Get operations would occasionally return corrupted results, sometimes it failed to return the record that is suppose to be there.

**Comment by petermattis** [comment]
@Ini Thanks for the report, but this is nearly impossible to debug given what you've provided. You've only vaguely described what your system is doing, and what operations are being performed. Can you share your test demonstrating the corruption? Can you provide a small reproducer demonstrating the corruption?

While developing https://github.com/cockroachdb/pebble/commit/b880baba077f45917be1f38961910d6d7438ae2e I encountered several cases of corruption, and they all turned out to be user error. For example: https://github.com/cockroachdb/pebble/blob/master/sstable/reader.go#L1087-L1094. Failing to copy the value before closing the iterator was always a bug, but GC of the cached data blocks made it less likely. If you're using `DB.Get`, I suspect that this same bug is present there (we're failing to copy the iterator value that is being returned before closing the iterator.

**Comment by lni** [comment]
@petermattis thanks for the quick response. 

I just realized that I had the Cache field of my pebble.Options set to pebble.NewCache(0). Interestingly, the above reported error stopped to reappear (or at least far less often) once the Cache field is left to use its default value. 

The behavior of pebble.Options {Cache: pebble.NewCache(0)} is also a little bit strange, it doesn't seem to disable the cache. When using the latest revision of pebble (9fa17a27f5d9d849ae4da919535c77f837dfcd2e), I keep getting the following error when pebble.Options {Cache: pebble.NewCache(0)} is used. The error is gone if the Cache field is left to use its default value. 

```
pebble: cache (0xc000020460) has non-zero reference count: 1
```

Does these ring any bell?

**Comment by petermattis** [comment]
The call to `NewCache` needs to be balanced with a call to `Cache.Unref`. The error you're getting is a guard-rail indicating that a `Cache` is not being unreferenced correctly.

> I just realized that I had the Cache field of my pebble.Options set to pebble.NewCache(0). Interestingly, the above reported error stopped to reappear (or at least far less often) once the Cache field is left to use its default value.

Are you using `DB.Get`? I'm pretty sure it has a bug right now. That bug was always present, but the manual cache memory management is just making it more obvious.

**Comment by petermattis** [comment]
@lni Does https://github.com/cockroachdb/pebble/pull/538 fix the corruption? 

> The behavior of pebble.Options {Cache: pebble.NewCache(0)} is also a little bit strange, it doesn't seem to disable the cache

Neither Pebble or RocksDB can run without any cache. `NewCache(0)` will evict blocks as soon as possible, but blocks need to be cached for short periods of time while reading. Are you seeing something else that is strange about using `NewCache(0)` other than the "non-zero reference count" error?

**Comment by lni** [comment]
@petermattis thanks for the fix and the explanations above. 

I tried #538, the above reported data corruption error is gone.
