### ISSUE TITLE
perf: continuous benchmarking before the performance improvement

### ISSUE THREAD

**Issue by hueypark** [cockroachdb/pebble#597]
We are very interested in the performance improvement of Pebble. But before do this we must measure performance and predict the effectiveness.

Recently, I introduced [continue benchmarking](http://marsettler.com/marsettler/benchmark/) with [Github Actions](https://github.com/hueypark/marsettler/blob/master/.github/workflows/benchmark.yml) and [gobenchdata](https://github.com/bobheadxi/gobenchdata) in my toy project. How about applying this continuous benchmark to Pebble?

**Comment by petermattis** [comment]
This is interesting.

Is your thinking that we'd run the Pebble microbenchmarks daily? Those benchmarks have varying levels of utility. Running all of them doesn't sound useful. I wonder if we could find a small subset that would be representative. Or create new benchmarks that are representative of various aspects of performance.

I experimented with GitHub Actions in the past and noticed that they run on fairly weak VMs. Has that changed?

**Comment by hueypark** [comment]
> Is your thinking that we'd run the Pebble microbenchmarks daily?

I think we had run the benchmark on every commit. Also, we should add notifications to warn of serious performance degradation.

> Those benchmarks have varying levels of utility. Running all of them doesn't sound useful. I wonder if we could find a small subset that would be representative. Or create new benchmarks that are representative of various aspects of performance.

I agree. I think we can add a more representative benchmark while editing #552.

> I experimented with GitHub Actions in the past and noticed that they run on fairly weak VMs. Has that changed?

No. It's still a [weak VM](https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources). If we want more accurate results, we need to prepare a more controlled environment rather than a GitHub Action.

**Comment by petermattis** [comment]
> I think we had run the benchmark on every commit. Also, we should add notifications to warn of serious performance degradation.
...
> I agree. I think we can add a more representative benchmark while editing #552.

A challenge here is that many interesting bits of performance only occur after running the system for hours. This is definitely true of the compaction heuristics. CockroachDB runs performance tests nightly. Trying to catch performance regressions by testing every commit feels like a bar too high.

I'm not terribly familiar with GitHub Actions. I experimented with them briefly in the past, but found the weak VM issue to be an irritant. Perhaps the right thing to do is to add Pebble-level benchmarks to the CRDB nightly framework, but then use something like `gobenchdata` to publish the results.

**Comment by petermattis** [comment]
Note that we do have the beginnings of longer running workloads in the `cmd/pebble` tool. See `pebble bench ycsb`.

**Comment by hueypark** [comment]
> Note that we do have the beginnings of longer running workloads in the cmd/pebble tool. See pebble bench ycsb.

I think `pebble bench ycsb` to be a good workload for this. We could make a visualization tool for that.

I can't do anything else because I don't have access to the nightly test. Let me know if you need anything.

**Comment by petermattis** [comment]
Did a bit of thinking and investigation on this topic. Notes below.

I took a look at how the `gobenchdata` action works. It runs the specified benchmarks, passes the output through `gobenchdata` (which is also a command line tool) in order to convert the output to json. The output from the new benchmark run is added to a `benchmarks.json` file that is added to the `gh-pages` branch in the repository. The static site itself is also served from the `gh-pages` branch using Github Pages. `chart.js` is used for the charting.

I don't think we could use this as-is for long-running tests. There is a high-level similarity in this setup to how `roachperf` (internal CRDB tool for tracking performance over time). For making data publicly available, there is something attractive about using Github Pages and storing the historical benchmark data in a Git branch. I don't think we currently give any nightly test permission to push to a Git repo, though. I'll have to track down whether doing so is problematic.

**Comment by hueypark** [comment]
Thank you for your kind sharing.
