### ISSUE TITLE
*: implement `SafeMessage` or equivalent for errors

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#598]
In CockroachDB, path names and other potentially sensitive information is optionally redacted from error messages by wrapping all RocksDB errors in [`storage.Error`](https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/error.go#L21). This type implements a `SafeMessager` interface, which is simply:

```
type SafeMessager interface {
	SafeMessage() string
}
```

We should audit the error handling in Pebble and either implement `SafeMessager` or ensure that the errors do not contain sensitive information.

**Comment by knz** [comment]
Ever since the SafeMessager interface has been introduced, strings inside error objects are *not* reported to Sentry by default *unless* the SafeMessager interface is used.

So if today the Pebble code does not use it that means that Pebble error strings are not sent to Sentry at all.

Caveat: it's OK as long as the code EITHER 

1) does not use `cockroachdb/errors`, OR 

2) uses `cockroachdb/errors` AND does not pass sensitive strings to `errors.New()` or the first argument to `errors.Newf` / `errors.Errorf`. 

Regarding (2): in practice, sensitive information—if any—is present only in the additional positional arguments to Newf/Errorf, not the first, so that should be fine. 

Feel free to audit this.

Finally, you may want to start using `errors.Safe()` to mark values in `errors.Newf`/`errors.Errorf` as safe for reporting, that will help with debugging.

**Comment by knz** [comment]
(NB: the `log.SafeMessager` interface is phased out for error objects, and will be for logging. Consider using `errors.Safe` for your error objects.)

**Comment by petermattis** [comment]
Pebble does not use `cockroachdb/errors` (yet). This is good motivation to do so.
