### ISSUE TITLE
Should not lock the database when in read only mode

### ISSUE THREAD

**Issue by esonic** [cockroachdb/pebble#757]
```
// Lock the database directory.
fileLock, err := opts.FS.Lock(base.MakeFilename(opts.FS, dirname, fileTypeLock, 0))
if err != nil {
	d.dataDir.Close()
	if d.dataDir != d.walDir {
		d.walDir.Close()
	}
	return nil, err
}
```

I am opening the DB in RW mode in one process and open the same DB in read only mode concurrently in another process. And I found above codes in `open.go`. It shows that no matter whether the DB is opened in read only mode, the FS.Lock function will always be called.

IMO, Lock should not be called when in read only mode, or else lock will fail if the DB has already been opened in RW mode in another process.

By the way, the default FS Lock implementation looks not work on my machine. A DB can be opened multiple times concurrently without error even in RW mode.

**Comment by petermattis** [comment]
> I am opening the DB in RW mode in one process and open the same DB in read only mode concurrently in another process. And I found above codes in open.go. It shows that no matter whether the DB is opened in read only mode, the FS.Lock function will always be called.
>
> IMO, Lock should not be called when in read only mode, or else lock will fail if the DB has already been opened in RW mode in another process.

Yes. Pebble's behavior here differs from RocksDB, though I fail to see how well this will work for RocksDB. A DB opened in read-only mode will not be aware of the changes caused by a DB opened in read-write mode. This can cause operations to fail in unexpected ways. For example, the read-write DB may delete an sstable that the read-only DB wants to read from. I can see an argument for allowing a DB to be opened in read-only mode multiple times, but exclusively with being opened in read-write mode. Sort of like the semantics of a `RWMutex`.

RocksDB does have support for ["secondary" DBs](https://github.com/facebook/rocksdb/wiki/Secondary-instance), but there is quite a bit of complexity to doing this and it is not something that would be added to Pebble any time soon.

> By the way, the default FS Lock implementation looks not work on my machine. A DB can be opened multiple times concurrently without error even in RW mode.

That is a bug. Can you provide more details? OS version? Distribution? Etc. Does `vfs.TestFileLock` pass on your machine.

**Comment by esonic** [comment]
> Yes. Pebble's behavior here differs from RocksDB, though I fail to see how well this will work for RocksDB. A DB opened in read-only mode will not be aware of the changes caused by a DB opened in read-write mode. This can cause operations to fail in unexpected ways. For example, the read-write DB may delete an sstable that the read-only DB wants to read from. I can see an argument for allowing a DB to be opened in read-only mode multiple times, but exclusively with being opened in read-write mode. Sort of like the semantics of a `RWMutex`.
> 
> RocksDB does have support for ["secondary" DBs](https://github.com/facebook/rocksdb/wiki/Secondary-instance), but there is quite a bit of complexity to doing this and it is not something that would be added to Pebble any time soon.

I got it. Thanks for reply.
 
> That is a bug. Can you provide more details? OS version? Distribution? Etc. Does `vfs.TestFileLock` pass on your machine.

This is my mistake, the code works fine.
