### ISSUE TITLE
db: backoff on repeated flush, compaction errors

### ISSUE THREAD

**Issue by karalabe** [cockroachdb/pebble#908]
I was playing with pebble a bit and left it to crunch some dataset. Later when I came back I saw that my disk got full. The interesting issue however was that pebble was printing "background" warning messages that it cannot allocate space for sst files, but nonetheless it was relentlessly compacting non stop. It generated terrabytes of compaction writes in a few hours, all whilst keeping printing the errors about the lack of space. I'm unsure what the behavior in this case should be and I could accept it retrying, hoping that some space got freed up, but the terrabytes of writes seems to indicate some bug.

**Comment by jbowens** [comment]
Thanks @karalabe for the report!

>  It generated terrabytes of compaction writes in a few hours, all whilst keeping printing the errors about the lack of space. 

Did Pebble actually _write_ terabytes while attempting these compactions or did it just attempt many compactions that would total terabytes if they were successful? If you're using [MakeLoggingEventListener](https://pkg.go.dev/github.com/cockroachdb/pebble#MakeLoggingEventListener) to gather logs and Pebble actually wrote sstables during these unfruitful compactions, you would see log lines like:
```
[JOB 55208] compacting: sstable created 057153
```
whereas the _start_ of a compaction produces log lines like:
```
[JOB 55208] compacting L5 [057151] (60 M) + L6 [057146] (47 M)
```  
---

As you observed, if a compaction fails Pebble reports the error through the configured `EventListener.BackgroundError` handler and then tries again. There are a couple TODOs in the code to backoff in the presence of repeated failures:

https://github.com/cockroachdb/pebble/blob/45470877be6eec0048dc49bce2f14df7f59fa2e3/compaction.go#L1667
https://github.com/cockroachdb/pebble/blob/45470877be6eec0048dc49bce2f14df7f59fa2e3/compaction.go#L1225

I retitled the issue to track that change. 

Also, it looks like when a compaction fails during `runCompaction`, we don't mark any discarded pending sstables as obsolete. Those tables would be 'leaked' until the next `Open` call removes them. If a compaction is persistently failing due to some non-fatal reason _other_ than out-of-space, it seems like Pebble could fill the filesystem with leaked obsolete tables: 
https://github.com/cockroachdb/pebble/blob/45470877be6eec0048dc49bce2f14df7f59fa2e3/compaction.go#L1705-L1717

**Comment by karalabe** [comment]
These are the IO charts from that particular run. The red line is when the disk got full. You can see that until then the database had various access patterns, but when the disk got full it just started to hammer it.

![Screenshot from 2020-09-17 20-43-51](https://user-images.githubusercontent.com/129561/93507788-dcff1700-f926-11ea-819a-9a36d5819c55.png)
