### ISSUE TITLE
MinCompactionRate and MinFlushRate should maybe be Max?

### ISSUE THREAD

**Issue by karalabe** [cockroachdb/pebble#911]
I'm a bit puzzled on these options:

```go
	// MinCompactionRate sets the minimum rate at which compactions occur. The
	// default is 4 MB/s.
	MinCompactionRate int

	// MinFlushRate sets the minimum rate at which the MemTables are flushed. The
	// default is 1 MB/s.
	MinFlushRate int
```

What does it mean to set the "minimum rate" :) Shouldn't this be maximum by any chance? It's used in the rate limiter.

**Comment by petermattis** [comment]
These options currently don't do anything. When they did do something, it was actually to set a minimum rate for flushing and compaction so that compaction/flushing pacing didn't use a rate below this value.

**Comment by karalabe** [comment]
What does it mean to have a minimum rate? What happens if I specify that I want 1TB/s minimum?

The code that uses these values is `rate.NewLimiter(rate.Limit(d.opts.MinCompactionRate), d.opts.MinCompactionRate)`. That to me seems like a pretty obvious upper limit for something.

```go
// NewLimiter returns a new Limiter that allows events up to rate r and permits
// bursts of at most b tokens.
func NewLimiter(r Limit, b int) *Limiter {
	return &Limiter{
		limit: r,
		burst: b,
	}
}
```

**Comment by petermattis** [comment]
> What does it mean to have a minimum rate? What happens if I specify that I want 1TB/s minimum?

It means that if compactions and flushing are not falling behind and we only need to trickle out writes for a compaction or flush, the this is the minimum rate at which to do so. If you set the value to 1TB/s then compactions/flushing would never be slowed down all. Note that the intention of these options is to pace compactions/flushing when write load is light. Under heavy write load Pebble performs compactions and flushing as fast as possible as that minimizes both write latency and the risk of "write stalls". If compaction/flushing still can't keep up with the incoming write load, your application is overloaded.

Lastly, note that this pacing stuff is currently all disabled because we discovered unacceptable overhead during performance benchmarking.

> The code that uses these values is rate.NewLimiter(rate.Limit(d.opts.MinCompactionRate), d.opts.MinCompactionRate). That to me seems like a pretty obvious upper limit for something.

Yes, but you also need to see how the limiter is used. We only utilize the limiter if compaction/pacing is "keeping up".

**Comment by karalabe** [comment]
Ah, I think I get it. Will dig into the code for more info if I need it (and when it gets eventually enabled). Thank you
