### ISSUE TITLE
How to iterate in reversed order?

### ISSUE THREAD

**Issue by ivanjaros** [cockroachdb/pebble#980]
I want to iterate in descending order(ie. ASC vs DESC indices) and i see that the iterator has the First() and Last() methods and Prev() and Next() methods but when I do not know the upper bound then how do I determine where to start?

With ascending iterator i can simply use the prefix and then check
```
if bytes.HasPrefix(iter.Key(), prefix) == false {
			break
		}
```

if i have reached the invalid prefix key. But for reversed order I have no way of knowing where to start.

Will the iterator support proper prefix scans in the future?

**Comment by petermattis** [comment]
> if i have reached the invalid prefix key. But for reversed order I have no way of knowing where to start.

I'm not sure I understand the problem, but [Example_prefixiteration](https://github.com/cockroachdb/pebble/blob/master/example_test.go#L39-L84) may contain the solution. If you're reverse iterating on a prefix, you'd want to `SeekLT(keyUpperBound(prefix))`. Actually, that example would probably work as is if you set up the Lower and Upper bounds exactly as it does, and then use `Last` and `Prev` instead of `First` and `Next`.

> Will the iterator support proper prefix scans in the future?

Not sure what proper prefix scans would look like. The existing functionality seems to allow for prefix scans in both directions.

**Comment by ivanjaros** [comment]
ok, sounds good. thanks.

By the "proper prefix scans" I mean something like Badger's iterator that has built-in support for prefixes and one does not have to write this additional logic. Simply put, i := Iterator{Prefix: prefix} and that's it, no upper or lower bound handling. It does it internally.
