### ISSUE TITLE
Operations on closed DB occur panic

### ISSUE THREAD

**Issue by ijsong** [cockroachdb/pebble#998]
Operations on closed DB occur panic:

```go
db, _ := pebble.Open("db", &pebble.Options{})
db.Close()
db.Get([]byte("k"))
```

In `(*DB).getInternal` and `(*DB).Apply`, it seems to be intended. But can it use `ErrClosed`?

- `getInternal`: https://github.com/cockroachdb/pebble/blob/master/db.go#L368-L371
- `Apply`: https://github.com/cockroachdb/pebble/blob/master/db.go#L531-L534
- `ErrClosed`: https://github.com/cockroachdb/pebble/blob/master/db.go#L42

**Comment by petermattis** [comment]
@ijsong The panic is intentional. Doing any operation on a closed DB is a programatic error that should be fixed as there is a race that is only avoidable with unacceptable synchronization overhead.

**Comment by ijsong** [comment]
@petermattis I understood it. Thank you.

**Comment by holiman** [comment]
I think this design-choice is unfortunate. 
Would it be possible to have a second method, e.g. `GetC`, which returns the error rather than `panic`?

**Comment by holiman** [comment]
In general, the shutdown-check in pebble is a bit optimistic. There is just a check on an atomic, `d.closed` at the start of `Get`. But it doesn't actually lock anything, so right after checking that atomic, a racing routine can `Close` the db anyway, which leads to a different `panic`:
``` 
panic: pebble: inconsistent reference count: -1

goroutine 1 [running]:
github.com/cockroachdb/pebble.(*flushableEntry).readerUnrefHelper(0xc000508820?, 0x0?, 0x0?)
        /home/user/go/src/github.com/cockroachdb/pebble/flushable.go:96 +0x13f
github.com/cockroachdb/pebble.(*flushableEntry).readerUnref(...)
        /home/user/go/src/github.com/cockroachdb/pebble/flushable.go:83
```

So I guess the behaviour is consistent: if it did guarantee to return error for "GetOnClosedDb", then it would also have to internally synchronize to ensure that `inconsistent reference count` panic does not occur. As it is, it forces the caller to handle that. 

I understand why the design-choice was made, but I still think it's a bit unfortunate; one could argue that it makes sense for pebble to implement the synchronization once rather than N projects all implementing their own synchronization on this particular topic.
